name: Build, Test, Lint, Docker Build

on: [push]
jobs:
  build-test:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest -q
      - name: Run Linter
        run: flake8 .
      - name: Build Docker Image
        run: docker build -t myapp:latest .
